name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: test
        type: choice
        options:
          - test
          - test_post
          - test_get

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test
        if: "github.event.inputs.deployment_target == 'test'"
        run: pytest  -v
      - name: test_post
        if: "github.event.inputs.deployment_target == 'test_post'"
        run: pytest tests/users/test_post.py -v
      - name: test
        if: "github.event.inputs.deployment_target == 'test_get'"
        run: pytest tests/users/test_get_accounts.py -v
